def app
pipeline {
    agent any
    environment {
        ENV_TYPE = "production"
        PORT = 3244
        NAMESPACE = "9art-ru"
        REGISTRY_HOSTNAME = "burshilya2023"
        PROJECT = "snapix-back-main"
        SERVICE="main"
        REGISTRY = "registry.hub.docker.com"
        DEPLOYMENT_NAME = "snapix-back-main-deployment"
        IMAGE_NAME = "${env.BUILD_ID}_${env.ENV_TYPE}_${env.GIT_COMMIT}"
        DOCKER_BUILD_NAME = "${env.REGISTRY_HOSTNAME}/${env.PROJECT}:${env.IMAGE_NAME}"
        ACCESS_TOKEN_SECRET = "${env.ACCESS_TOKEN_SECRET}"
        REFRESH_TOKEN_SECRET = "ki9082uijn809dfumdosufh9wefwedf"
        DATABASE_URL = "postgresql://muzyk0:wEHaoK5SqWD8@ep-dawn-firefly-962824.us-east-2.aws.neon.tech/snapix-test?sslmode=require"
        SHADOW_DATABASE_URL = "postgresql://muzyk0:wEHaoK5SqWD8@ep-dawn-firefly-962824.us-east-2.aws.neon.tech/snapix-shadow?sslmode=require"
        RMQ_URLS = "${env.RMQ_URLS}"
    }

    stages {
        stage('Clone repository') {
            steps {
                checkout scm
            }
        }
        stage('Install dependency') {
            steps {
                script {
                    sh "yarn install"
                }
            }
        }
        stage('Generate Prisma') {
            steps {
                script {
                    sh "yarn main:prisma:generate"
                }
            }
        }
        stage('Typescript Check') {
            steps {
                script {
                    sh "yarn tsc"
                }
            }
        }
        stage('Lint Check') {
            steps {
                script {
                    sh "yarn lint:check"
                }
            }
        }
        stage('Unit tests') {
            steps {
                script {
                    sh "yarn test:main"
                }
            }
        }
        stage('e2e tests') {
            steps {
                script {
                    sh "yarn test:main:e2e"
                }
            }
        }
        stage('Build docker image') {
            steps {
                echo "Build image started..."
                    script {
                       app = docker.build("${env.DOCKER_BUILD_NAME}", "--build-arg service=${env.SERVICE} --build-arg port=${env.PORT} -f ./apps/${env.SERVICE}/Dockerfile ./")
                    }
                echo "Build image finished..."
            }
        }
        stage('Push docker image') {
             steps {
                 echo "Push image started..."
                     script {
                        docker.withRegistry("https://${env.REGISTRY}", '9art-ru') {
                            app.push("${env.IMAGE_NAME}")
                        }
                     }
                 echo "Push image finished..."
             }
       }
       stage('Delete image local') {
             steps {
                 script {
                    sh "docker rmi -f ${env.DOCKER_BUILD_NAME}"
                 }
             }
        }
        stage('Preparing deployment') {
             steps {
                 echo "Preparing started..."
                     sh 'ls -ltr'
                     sh 'pwd'
                     sh "chmod +x ./apps/${env.SERVICE}/preparingDeploy.sh"
                     sh "./apps/${env.SERVICE}/preparingDeploy.sh ${env.REGISTRY_HOSTNAME} ${env.PROJECT} ${env.IMAGE_NAME} ${env.DEPLOYMENT_NAME} ${env.PORT} ${env.NAMESPACE}"
                     sh "cat ./apps/${env.SERVICE}/deployment.yaml"
             }
        }
        stage('Deploy to Kubernetes') {
             steps {
                 withKubeConfig([credentialsId: 'prod-kubernetes']) {
                    sh "kubectl apply -f ./apps/${env.SERVICE}/deployment.yaml"
                    sh "kubectl rollout status deployment/${env.DEPLOYMENT_NAME} --namespace=${env.NAMESPACE}"
                    sh "kubectl get services -o wide"
                 }
             }
        }
    }
}
